### ISSUE TITLE
User Story - SEO 

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#17]
As a **Site Owner**, I would like **The site to have all the content needed to perform well in SEO**, so that **ultimately the site has the ability to perform well in search results and can be found**
### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that the site is deployed
    **When** the spiders visit the site
    **Then** there is a sitemap to guide them
-	Acceptance Criteria 2
    **Given** that content is written for the site
    **When** it is written
    **Then** the keyword research is utilised to ensure relevant information is included

### Tasks
-	[x] Task 1 – Conduct Keyword Research prior to planning out the site
-	[x] Task 2 – From Keyword Research plan content requirements for the site
-	[x] Task 3 – From keyword research plan site content
-	[x] Task 4 – Create sitemap.xml file utilising [www.xml-sitemaps.com](http://www.xml-sitemaps.com/)
-	[x] Task 5 – Place sitemap.xml file in root directory
-	[x] Task 6 – Create robots.txt file
### Epic: #2

**Comment by MattBCoding** [comment]
Tasks 4, 5 + 6 completed on commit 1f6f4bcafbed1599265a02c1d1803a7ae9e10f4d
Tasks 1, 2, 3 completed prior to repo inception
Meta tags and keywords added on commit 3dd2efa542cf9037720837f485e351688bd21910
