### ISSUE TITLE
User Story - Create Account

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#20]
As a **User**, I would like **to be able to create an account**, so that **I don’t have to enter my details every time I place an order**
### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an unregistered user
 	And, I am on the user registration page
    **When** I enter my email address and password
	And, I click on the register button
    **Then** the system creates me an account
	And, it tells me that my account has been created
-	Acceptance Criteria 2
    **Given** that I have an account
	And, I have items in my cart
    **When** I navigate to checkout
    **Then** I have my address information ready to be used
-	Acceptance Criteria 3
    **Given** that I have an account
	And, I try to navigate to the register page
    **When** I enter my email address and password
	And, I click on the register button
    **Then** the site tells me that I already have an account

### Tasks
-	[x] Task 1 – Develop the ability for users to register for an account
-	[x] Task 2 – Develop ability for users to save details to their account such as address
-	[x] Task 3 – Prevent multiple accounts being created for the same email address

**Comment by MattBCoding** [comment]
Task 1 completed on commit 1920a35a315de318a5186865957f55419d120fe0

**Comment by MattBCoding** [comment]
Task 2 completed on commit 4cb3853242f1a951bdd48c1e931a96443289c966

**Comment by MattBCoding** [comment]
Task 3 completed via built in functionality
