### ISSUE TITLE
User Story - Edit Account

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#21]
As a **User**, I would like **to be able to edit the details/address stored on my account**, so that **If I move, or if I want to use more than one address, I can store them all**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I have a user profile,
	And, I am logged into my profile
    **When** I navigate to my profile
    **Then** I have the ability to add different addresses on my account
-	Acceptance Criteria 2
    **Given** that I have a user profile,
	And, I am logged in
    **When** I navigate to my profile
	And, I have more than one address stored
    **Then** I can select one to be the default address
-	Acceptance Criteria 3 
    **Given** that I have a user profile,
	And, I am logged into my profile
    **When** I navigate to my profile
    **Then** I have the ability to edit the address’s
-	Acceptance Criteria 4
    **Given** that I have a user profile,
	And, I am logged into my profile
    **When** I navigate to my profile
    **Then** I have the option to delete the address’s

### Tasks
-	[x] Task 1 – Develop the ability for users to save addresses to their profile
-	[x] Task 2 – Develop the ability for users to store more than one address on their profile
-	[x] Task 3 – Develop the ability for users to set one address as default
-	[x] Task 4 – Develop the ability for users to edit the addresses on their profile
-	[x] Task 5 – Develop the ability for users to delete the addresses on their profile

**Comment by MattBCoding** [comment]
Task 1 + 2 completed on commit 3a0e98ec1161bb6a93ac397bb1e49f3e7c7eb3af

**Comment by MattBCoding** [comment]
Task 4 completed on commit 412a62821b7cfa34a855a700c901c94c33db7b82

**Comment by MattBCoding** [comment]
Task 5 completed on commit 4cb3853242f1a951bdd48c1e931a96443289c966
