### ISSUE TITLE
User Story - View Account

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#22]
As a **User**, I would like **to be able to view the details stored on my account**, so that **I can review what is stored**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I have a user account
    **When** I am logged into my account
    **Then** I have an option to view my account
-	Acceptance Criteria 2
    **Given** that I have a user account
	And, I am logged in
    **When** I navigate to view my details
    **Then** everything that is stored within my account is available to be viewed
-	Acceptance Criteria 3
    **Given** that I have a user account
    **When** I navigate to the url to view my account whilst not logged in
    **Then** I am redirected to the login page and I’m unable to view the details without being logged in

### Tasks
-	[x] Task 1 – Develop a link in the menu that takes logged in users to their profile
-	[x] Task 2 – Develop a link within the user profile page that they can use to view all other information associated with the account – previous orders, wishlist items
-	[x] Task 3 – Restrict access to account details to logged in users – specifically the user who’s details they are.

**Comment by MattBCoding** [comment]
Completed on commit 6e020947aae74a3d130271d0037c6b9756767407
