### ISSUE TITLE
User Story - Delete Account

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#23]
As a **User**, I would like **to be able to delete my account**, so that **I have full control over the information that is stored about me**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I have a user account
    **When** I view my account details whilst logged in
    **Then** I have the option to delete my account.
-	Acceptance Criteria 2
    **Given** that I have a user account
	And, I am on my account details page
    **When** I select to delete my account
	And, I confirm the deletion request
    **Then** My account is deleted.

### Tasks
-	[ ] Task 1 – On the user profile page provide an option to delete account
-	[ ] Task 2 – require a second confirmation for account deletion
-	[ ] Task 3 – develop method to delete the account when the user requests it to be deleted – will need to keep order history separately for company records.

**Comment by MattBCoding** [comment]
Tasks 1 + 2 completed on commit 4cd19884bd385a4d7af410983a5801467a49842a
Task 3 requires order history to be configured.
