### ISSUE TITLE
User Story - Account Login

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#25]
As a **User**, I would like **to be able to login to my account**, so that **I can access the advantages of having an account**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a registered user
    **When** I navigate to the login page
    **Then** I can enter my details to login to my account
-	Acceptance Criteria 2
    **Given** that I am a registered user
    **When** I navigate to the login page and enter my details
	And, I click login
    **Then** I am logged into my account and I am able to see a visual confirmation that I am now logged in
-	Acceptance Criteria 3
    **Given** that I am a registered user
	And, I try to log in to my account
    **When** I enter the wrong information
    **Then** the site informs me that the information was incorrect and prevents my logging in

### Tasks
-	[x] Task 1 – Develop a link to a login page
-	[x] Task 2 – Develop a login form for users to confirm their log in details
-	[x] Task 3 – Develop form validation to ensure the data is entered correctly
-	[x] Task 4 – Develop a method to validate the data entered matches a user account
-	[x] Task 5 – Develop a redirect so unlogged in users are redirected to the login page when trying to access pages that require the user to be logged in.

**Comment by MattBCoding** [comment]
Tasks 1 - 4 completed on commit 848c161d2d789c0de9adc6d9daba0668a724b8c6

**Comment by MattBCoding** [comment]
Task 5 functionality included within django - redirects to login page.
