### ISSUE TITLE
User Story - Account Logout

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#26]
As a **User**,  I would like **to be able to log out of my account**, so that **I can keep my account secure**

### Acceptance Criteria
-	Acceptance Criteria 1
     **Given** that I am logged into my account
    **When** I click on the logout link
    **Then** I am asked to confirm to logout
-	Acceptance Criteria 2
    **Given** that I am a logged in user who has clicked logout
    **When** I confirm I want to logout
    **Then** I am logged out of my account
- Acceptance Criteria 3
    **Given** that I am a registered user, who has signed out of my account
    **When** I use the browser navigation buttons such as back button
    **Then** I cannot access information which requires me to be signed in

### Tasks
-	[x] Task 1 – Develop link for users to access logout functionality
-	[x] Task 2 – Develop logout confirmation form to log users out
-	[x] Task 3 – Develop a redirect so if a user signs out whilst on a page requiring a user to be logged in, it redirects them appropriately

**Comment by MattBCoding** [comment]
Tasks 1 + 2 completed on commit a70e4faa1603b0a0b8d30b94eb0887b3dd7f4e83

**Comment by MattBCoding** [comment]
Task 3 - unnecessary - sign out functionality located on own page. User is required to navigate to sign out page in order to sign out. If user has page that requires them to be logged in open on another tab it will remain open until they navigate away from that page - or try to submit a form.
