### ISSUE TITLE
User Story - Account - Social login

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#27]
As a **User**, I would like **to be able to use my social media account**, so that **I can create an account without typing in details**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an unregistered user
    **When** I navigate to the registration page
    **Then** I should have the option to register using my social media account
-	Acceptance Criteria 2
    **Given** that I am an unregistered user
    **When** I select the register using my social media account option
    **Then** An account should be created using the social media credentials
-	Acceptance Criteria 3
    **Given** that I am an unregistered user
    **When** I register using my social media account
	And, an account is created for me
    **Then** I should have the ability to sign into my account using my social media account credentials

### Tasks
-	[ ] Task 1 – Develop the ability for users to utilise their google account to register for a user account
-	[ ] Task 2 – Develop the ability for users to utilise their google account to sign into their account
-	[ ] Task 3 - Develop the ability for users to utilise their apple account to register for a user account
-	[ ] Task 4 – Develop the ability for users to utilise their apple account to sign into their account
-	[ ] Task 5 – Develop the ability for users to utilise their facebook account to register for a user account
-	[ ] Task 6 – Develop the ability for users to utilise their facebook account to sign into their account
