### ISSUE TITLE
User Story - Add Products

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#28]
As an **Store Owner**, I would like **employees to be able to add new products to the site easily**, so that **the site can be kept upto date**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am an employee
    **When** I log into the site
    **Then** I should have additional stock management options available
-	Acceptance Criteria 2
    **Given** That I am a logged in employee
    **When** I select add product
    **Then** I should be directed to a form that allows me to add a new product to the site
-	Acceptance Criteria 3
    **Given** That I am a logged in employee
	And, I have completed the form to add a product
    **When** I submit the form
    **Then** the new product should appear on the site

### Tasks
-	[x] Task 1 – Develop a separate navigation bar for employee users to allow access to other site areas
-	[x] Task 2 – Develop a form for employees to add products to the site
-	[x] Task 3 – Develop validation to ensure that product information is completed correctly
-	[x] Task 4 – Develop the backend to process the form data and create a new product file/page to be added to the site

**Comment by MattBCoding** [comment]
completed on commit f9f02505722dd3c7367d8dfaf72003f842ce5f79
