### ISSUE TITLE
User Story - Edit Products

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#29]
As a **Store Owner**, I would like **employees to be able to edit product details on the site easily**, so that **any corrections needed can be carried out when required**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am an employee
    **When** I log into the site
    **Then** I should have the option to edit a product
-	Acceptance Criteria 2
    **Given** That I am a logged in employee
    **When** I select edit product
    **Then** I have the ability to choose which product to edit
-	Acceptance Criteria 3
    **Given** That I am a logged in employee
    **When** I select which product to edit
    **Then** I am directed to a form from which I can edit the existing product data
-	Acceptance Criteria 4
    **Given** That I am a logged in employee
    **When** I edit product details within the form and submit the changes
    **Then** the changes I made appear on the site

### Tasks
-	[x] Task 1 – Develop the option for employees to edit products
-	[x] Task 2 – Develop a page for employees to select which product to edit
-	[x] Task 3 – Develop a form for employees to edit the product data
-	[x] Task 4 – Develop validation for the form to ensure product information is complete

**Comment by MattBCoding** [comment]
completed on commit 3effc1482ba07c11a3b94b1cfd30cc0709e19558
