### ISSUE TITLE
User Story - Delete Products

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#30]
As a **Store Owner**, I would like **employees to be able to remove product details from the site**, so that **we can remove no longer available products from the site**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an employee
    **When** I select a product to edit,
    **Then** I should have the option to remove it from the store
-	Acceptance Criteria 2
    **Given** that I am an employee
    **When** I select a product to remove from the store,
    **Then** I should also have the option to delete the product entirely
-	Acceptance Criteria 3
    **Given** that I am an employee
    **When** I have selected to remove a product from the store
    **Then** the product should not appear available to purchase but should remain in the database in case it will be added back at a later date
-	Acceptance Criteria 4
    **Given** that I am an employee
    **When** I have selected to delete a product entirely
    **Then** the product is removed from the database

### Tasks
-	[ ] Task 1 – Develop an option in the employee product listing to remove the product from the store
-	[ ] Task 2 – Develop an option in the employee product listing to delete the product from the database – can only be totally deleted if no relationships are in use – so if product has been ordered by customers – and appears on an order record we will still want to keep those details within the order. – deleted products – should not be referenced anywhere on the site. 
-	[ ] Task 3 – Restrict access to the option to employees only

**Comment by MattBCoding** [comment]
Task 1 and 3 completed on commit 2998bfe9d508ea0a8d0cb4d19eddbb7fe861320a
