### ISSUE TITLE
User Story - Order update

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#31]
As a **Site Owner**, I would like **employees to be able to update customer orders**, so that **customers are kept informed as to the status of their order**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an employee who is logged in
    **When** I am on the site, I can access customer orders
    **Then** I can select an order to update the status
-	Acceptance Criteria 2
    **Given** that I am an employee who is logged in
	And, I have selected an order to update its status
    **When** I am on the order details I have the new status options available
    **Then** When I select one, the status updates

### Tasks
-	[x] Task 1 – Develop the option for employees to update order status
-	[x] Task 2 – Develop the display of orders for employees to filter through
-	[x] Task 3 – Develop filtering capability to ease accessing the correct order for employees
-	[x] Task 4 – Develop an order status update form for employees to update the order status
-	[x] Task 5 – Develop validation for the order status form
-	[x] Task 6 – Restrict access to the order status screens to employees

**Comment by MattBCoding** [comment]
Task one completed on commit 7a29f1ea03960bf35c826955e11300d6da535715
Task two completed on commit 77d664e9cecf9200ec11f02ded6f19df3fd6989d
Task three completed on commit 77d664e9cecf9200ec11f02ded6f19df3fd6989d
Task four, five and six completed on commit f157e4a11dccb1f1f561133bfd50c3dd0101914b
