### ISSUE TITLE
User Story - Edit Stock

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#33]
As a **Site Owner**, I would like **employees to be able to edit the stock level of products contained within the system**, so that **if the stock level decreases offline for any reason, it can be reflected online correctly**.

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an employee
    **When** I am logged in, I have the option to edit stock on the system
    **Then** I can edit the current stock values for different products, all in one form
-	Acceptance Criteria 2
    **Given** that I am an employee
	And, I am logged in
    **When** I go to edit stock for a product
    **Then** I can filter through the products to find the one I want
-	Acceptance Criteria 3
    **Given** that I am an employee
    **When** I adjust the stock level of a product
    **Then** the changes are reflected to users on the site

### Tasks
- [ ] Task 1 - Develop ability to edit the stock levels of a product
- [ ] Task 2 - Develop ability to edit all product stock levels
- [ ] Task 3 - Develop validation to confirm changes
- [ ] Task 4 - Develop restricted access to the edit stock functionality
