### ISSUE TITLE
User Story - View Stock

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#34]
As a **User**, I would like **to know if the product I want is in stock**, so that **I can be confident that I’ll get my order**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a User
    **When** I am on the site
    **Then** I can see if a product is in stock or not
-	Acceptance Criteria 2
    **Given** that I am a user
    **When** I look at a product detail page
	And, the product is out of stock
    **Then** I should be able to see when it will be back in stock

### Tasks
-	[ ] Task 1 – Add section to product card and detail pages that displays stock level
-	[ ] Task 2 – Develop different indicators for stock levels, low stock – less than 3, normal – less than 10, good – 10 plus.
-	[ ] Task 3 – Develop stock deduction when order confirmed – maybe on payment confirmation
