### ISSUE TITLE
User Story - View Product Details

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#35]
As a **User**, I would like to **be able to view the full details for a product**, so that **I can make an informed purchase decision**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am a user on the site
    **When** I navigate to a product listing
    **Then** the full details of the product are available
-	Acceptance Criteria 2
    **Given** That I am a user on the all products page
    **When** I click on a product summary card
    **Then** I am taken to a page with the full details on the product

### Tasks
-	[x] Task 1 – Develop a product full details page template
-	[x] Task 2 – Develop product card template
-	[x] Task 3 – Link product card with product detail page
