### ISSUE TITLE
User Story - Product Cards

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#36]
As a **User**, I would like to **be able to view summary details of a product**, so that **I can quickly narrow down the products that I am interested in**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am a User
    **When** I search for a product
    **Then** the products are displayed in a summary format
-	Acceptance Criteria 2
    **Given** That I am a user
    **When** I view the search results or product listing page
    **Then** all products matching the query, or all products are visible

### Tasks
-	[x] Task 1 -  Develop product summary details page template
-	[x] Task 2 – Develop pagination so that product summary page doesn’t get too large in the future
-	[ ] Task 3 – Develop user controlled filter to allow for more or less products to appear on each page

**Comment by MattBCoding** [comment]
Task 2 completed on commit f012fbbb9b82a1496858a3627f73fe8178c64221
Task 3 to be added at a later date
