### ISSUE TITLE
User Story - Product Search

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#37]
As a **User**, I would like to **be able to search for products**, so that **I can find the product I am looking for easily**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am a User
    **When** I am on the site
    **Then** I have easy access to search functionality
-	Acceptance Criteria 2
    **Given** That I am a User
    **When** I search for a product by name
    **Then** the product appears in the search results
-	Acceptance Criteria 3
    **Given** That I am a User
    **When** I search for a product by category
    **Then** all the products in that category appear

### Tasks
-	[x] Task 1 – Develop search bar functionality that is easy to access on every page
-	[x] Task 2 – Develop search query filter to search by product name
-	[x] Task 3 – Develop search query filter to search by category
