### ISSUE TITLE
User Story - Product Images

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#39]
As a **User**, I would like to **look at images of products from multiple angles**, so that **I have a good idea of what the product will look like on delivery**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am a user
    **When** I view a products full detail page
    **Then** I have multiple images to view
-	Acceptance Criteria 2
    **Given** That I am a user
    **When** I view the products details page on a mobile device
    **Then** it is easy to scroll through the images available
-	Acceptance Criteria 3
    **Given** That I am a user
    **When** I select another image to view
    **Then** the image becomes large enough to see

### Tasks
-	[x] Task 1 – Develop an image carousel or alternative image scroller to allow multiple images to appear for each product
-	[x] Task 2 – Include image carousel on products that have more than one image available
-	[x] Task 3 – image carousel needs to be accessible via a touch device
-	[x] Task 4 – image carousel needs to be accessible via a keyboard
-	[x] Task 5 – Develop control for user to select which image displays

**Comment by MattBCoding** [comment]
Completed on commit 27a663a6bb9c4f98454f70466c54b3093af5a1dc
