### ISSUE TITLE
User Story - Add Product to Wishlist

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#40]
As a **User**, I would like **to be able to add products I want to buy in the future to a wishlist**, so that **I can quickly access the products at a later date**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am a registered User
    **When** I view a product
    **Then** I have the option to add the product to my wishlist
-	Acceptance Criteria 2
    **Given** That I am an unregistered User
    **When** I view a product
	And, I try to add the product to my wishlist
    **Then** I receive a message telling me to login/register to save products to your wishlist

### Tasks
-	[x] Task 1 – Develop a wishlist model linked to user
-	[x] Task 2 – Develop a simple button that adds products to user’s wishlist
-	[ ] Task 3 – Develop a message to unregistered users to inform them that the wishlist is available to registered/logged in users
-	[x] Task 4 – Develop a visual indicator to users to inform them that the product is on their wishlist

**Comment by MattBCoding** [comment]
Tasks one, two and four completed on commit d82ba2e1c9f4c4468c6b9efb7d3db9e446c63661
Task three deemed unnecessary, add to wishlist buttons only available to registered users.
