### ISSUE TITLE
User Story - Remove product from wishlist

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#41]
As a **User**, I would like **to be able to remove products from my wishlist**, so that **I can remove products that I no longer wish to purchase in the future**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am a registered User
    **When** I navigate to my wishlist
    **Then** I can remove products from my wishlist
-	Acceptance Criteria 2
    **Given that I am a registered User
    **When** I navigate to a product that is on my wishlist
    **Then** I can remove it from my wishlist
-	Acceptance Criteria 3
    **Given** that I am a registered User
    **When** I want to access my wishlist
    **Then** there is a convenient link easily located to access it

### Tasks
-	[x] Task 1 – Develop a wishlist page template to display users saved items
-	[x] Task 2 – Develop ability for users to remove products from the wishlist on the wishlist page
-	[x] Task 3 – Develop ability for users to remove products from the product page
-	[x] Task 4 – Develop link for users to access wishlist page easily
-	[x] Task 5 – Develop ability for users to easily remove products from wishlist that they have purchased

**Comment by MattBCoding** [comment]
Tasks one, two, four and five completed on commit da0cc47d8cf3a27605beff002f3eb9521c047e3c
Task three completed on commit d82ba2e1c9f4c4468c6b9efb7d3db9e446c63661
