### ISSUE TITLE
User Story - Add to Cart

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#43]
As a **User**, I would like **to be able to add products that I want to buy to my shopping cart**, so that **I can proceed to purchase them**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am an unregistered user
    **When** I find a product I want to purchase
	And, I click on add to cart
    **Then** the product is added to my shopping cart, ready for me to purchase
-	Acceptance Criteria 2
    **Given** That I am a registered logged in user
    **When** I find a product I want to purchase, and click add to cart
    **Then** the product is added to my shopping cart, ready for me to purchase
-	Acceptance Criteria 3
    **Given** that I am a User,
    **When** I click add to cart on a product I have previously added to my cart
    **Then** The quantity of that product in my cart increases by the amount I just added
-	Acceptance Criteria 4
    **Given** that I am a registered user who is not logged in
    **When** I add products to my cart,
	And, **then** log in to my account
    **Then** the products I added remain in my cart ready for me to purchase

### Tasks
-	[x] Task 1 – Develop a shopping cart functionality to track products users want to purchase.
-	[x] Task 2 – Enable the cart to be utilised when a user is logged in or not
-	[x] Task 3 – Develop check on add to cart functionality for product already existing in cart – if product exists, increase quantity appropriately
-	[x] Task 4 – Develop ability for logged out user to login without losing cart contents.

**Comment by MattBCoding** [comment]
Task one completed on commit 0ec9ee6db7ddb5fd5956157169302f6a04f0141d
Task two completed on commit 0ec9ee6db7ddb5fd5956157169302f6a04f0141d
Task three completed on commit 72583c66edf2211f0f54bb43da984a122137d59c
Task four completed on commit 0ec9ee6db7ddb5fd5956157169302f6a04f0141d
