### ISSUE TITLE
User Story - Fill out address details for checkout

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#48]
As a **User**, I would like **to be able to provide my details**, so that **I can complete my order**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a User,
    **When** I proceed to checkout
    **Then** I am asked to enter my delivery and billing address
-	Acceptance Criteria 2
    **Given** that I am a user,
    **When** I enter my billing address
    **Then** I can use the same address for delivery without having to fill it out twice
-	Acceptance Criteria 3
    **Given** that I am a logged in user,
    **When** I enter my address details,
    **Then** I have the option to save the details I entered to my account
-	Acceptance Criteria 4
    **Given** That I am a logged in user,
    **When** I get to the enter billing and delivery address screen
    **Then** I have the option to use previously saved address(es) details
-	Acceptance Criteria 5
    **Given** That I am a registered user, not logged in
    **When** I progress to enter the address information – I have the ability to login
    **Then** return to the same screen and use previously saved address details.

### Tasks
-	[x] Task 1 – Develop checkout page to collect billing and delivery address details
-	[x] Task 2 – Enable option to use billing address for delivery address
-	[x] Task 3 – Enable option for users to save address details to their account
-	[x] Task 4 – Enable link to login which redirects back to checkout page
-	[x] Task 5 – Enable logged in users to select previously saved addresses instead of manual completion of the form

**Comment by MattBCoding** [comment]
Task one completed on commit c6ca7f1e59d90bd15a30b69a62e71341e1703a01
Task 2 moved to future development plans, currently site utilises one address for both billing and shipping.
Task 4 completed via allauth configuration
Task 5 completed on commit 5dc6c4f0853741f6131e9fc1745431b81d768501

**Comment by MattBCoding** [comment]
Task 3 completed on commit 45a66dec197c312c45d564f4cf68ed4f58900ae6
