### ISSUE TITLE
User Story - Create Account in Checkout

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#49]
As a **User**, I would like to **be able to create an account at the same time as processing my purchase**, so that **I can save the details of my purchase to my account**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an unregistered user
    **When** completing the checkout form with my address details
    **Then** I have the option to sign up as a user
-	Acceptance Criteria 2
    **Given** that I am a user
    **When** I select the option to sign up for an account at the same time as completing my purchase
    **Then** an account is created for me using the details I provided during my purchase

### Tasks
-	[ ] Task 1 – Develop the option for users to sign up for an account whilst completing a purchase
-	[ ] Task 2 – develop a form that will display fields required for user sign up at the same time as checkout if additional information is required
-	[ ] Task 3 – Develop link from purchase to new account to save purchase details to users account
