### ISSUE TITLE
User Story - Payment

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#50]
As a **User**, I would like **to be able to use my credit card to make the purchase**, so that **I can pay for the purchase easily**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a user
    **When** purchasing my items
    **Then** I have the ability to enter my credit card details on a secure form
-	Acceptance Criteria 2
    **Given** that I am a user
    **When** I enter my card details to pay for the transaction
    **Then** the system will process the payment
-	Acceptance Criteria 3
    **Given** that I am a user
    **When** I process the payment using my card details
    **Then** I am kept informed as to the status as it progresses
-	Acceptance Criteria 4
    **Given** that I am a user
    **When** My payment fails
    **Then** I am returned to the checkout page without losing all the inputted information
-	Acceptance Criteria 5
    **Given** that I am a user
    **When** I checkout and my payment is successful
    **Then** I am taken to a confirmation page

### Tasks
-	[x] Task 1 – Develop secure form to capture credit card details
-	[x] Task 2 – Develop link to payment processor
-	[x] Task 3 – Develop message system to keep customer informed of processing status
-	[x] Task 4 – Develop redirect to appropriate page depending on payment outcome

**Comment by MattBCoding** [comment]
All tasks completed on commit 33c1199fe2ffbe2486e8ac7ea5fd9e1fedbe6c6d
