### ISSUE TITLE
User Story - Order Confirmation

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#51]
As a **User**, I want to **be taken to a confirmation page when my order is completed**, so that **it is clear my order has gone through**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a user
    **When** I complete a checkout form and my payment is processed
    **Then** I can see confirmation of my order details
-	Acceptance Criteria 2
    **Given** that I am a user
    **When** I complete a checkout form and my payment is processed
    **Then** I receive an email with the confirmation details
-	Acceptance Criteria 3
    **Given** that I am a user
    **When** I complete a checkout form and my payment is processed
    **Then** an order number is generated with which I can retrieve the order details
-	Acceptance Criteria 4
    **Given** That I am a registered user, logged in when I placed my order
    **When** I have successfully completed my order
    **Then** the order appears in my orders of my account

### Tasks:
-	[x] Task 1 – Develop an order confirmation page that the user redirects to on order completion.
-	[x] Task 2 – Develop automated email confirming order – email to include link to order details page for that order and order number
-	[x] Task 3 – Develop order finder which can bring up the order details from the order number – possible data restriction here – might not be able to display the customer details.
-	[x] Task 4 – Develop linking new order to user orders so that it is visible within their order history on their account.
-	[x] Task 5 – Develop order number generator so each number has a unique identifier

**Comment by MattBCoding** [comment]
Task one and two completed on commit 3c7cb3036c4cce301edd9ffd791685ff57b8a248
Task 3 completed on commit 57757566ac33c974d0fe9a9cdd24a35f3d0791e4
Task 4 completed on commit 42585d9f2eb88a04d07bcfea982d787a1e793f7b
Task 5 completed on commit 93ca4db84160df105d29fe747942deb216a4a1e5
