### ISSUE TITLE
User Story - Check Order Status

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#52]
As a **User**, I would like **to be able to check on the status of my order**, so that **I know when it has shipped or when it will be arriving**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a user
    **When** I want to check on the status of my order
    **Then** there is an location where I can enter my order number to bring up its current status
-	Acceptance Criteria 2
    **Given** that I am a logged in user
    **When** I want to be able to check on a previous order
    **Then** there is a list of all my previous orders that will take me to the order status results

### Tasks
-	[x] Task 1 – Develop an order status system that returns the current status of an order
-	[x] Task 2 – Develop employee ability to update order status
-	[x] Task 3 – Develop link on user account to view order status for prior orders

**Comment by MattBCoding** [comment]
Task one and two completed on commit f157e4a11dccb1f1f561133bfd50c3dd0101914b
Task three completed on commit 42585d9f2eb88a04d07bcfea982d787a1e793f7b
