### ISSUE TITLE
User Story - Respond to Review

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#57]
As a **Employee**, I want to **be able to respond to a user’s review**, so that **where appropriate, concerns or compliments can be responded to**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That a User posts a review on a product
    **When** an Employee views the review
    **Then** they have the option to leave a response
-	Acceptance Criteria 2
    **Given** That an employee posts a response to a review
    **When** other users view that review
    **Then** they can read the response
-	Acceptance Criteria 3
    **Given** That an employee posts a response to a review
    **When** that employee, or other employees view the response
    **Then** they have the ability to edit or delete it.

### Tasks
-	[x] Task 1 – Develop a method for employees to respond to a review left on the site
-	[x] Task 2 – Develop a method for employees to edit or delete responses left on the site
-	[x] Task 3 – Develop the ability for all users to view the response from the company

**Comment by MattBCoding** [comment]
Task 1 completed on commit 8edc2596df0efd15aed9f66b1294ed7f3eeb8a34
Task 2 completed on commit 1832d76c4620df23adacb333a1c8565fcee40520 and commit 3e349b7a60bd0d97ab5be8c1e1a47ae58a672b2f
Task 3 completed on commit 4c07282ad87761017bdfd23aec596ca4b7545111
