### ISSUE TITLE
User Story - Email Capture

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#58]
As a **Site Owner**, I would like **to capture user emails**, so that **I can use them for marketing newsletters to promote new products**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** That I am a user who wants to subscribe to a newsletter
    **When** I complete the newsletter sign up form
    **Then** My email address is added to the newsletter distribution list
-	Acceptance Criteria 2
    **Given** That I am the site owner
    **When** I want to send a newsletter out
    **Then** I have a platform from which to do so to the database of emails collected

### Tasks
-	[x] Task 1 – Develop email sign up form to subscribe to newsletter
-	[x] Task 2 – Link email sign up form with mailchimp to collect email addresses
-	[ ] Task 3 – Identify logged in users – replace form with checkbox or alternative solution to subscribe to newsletter

**Comment by MattBCoding** [comment]
Task 3 deemed unnecessary - email marketing utilises mailchimp form to capture email addresses.
