### ISSUE TITLE
User Story - View Blog Post

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#61]
As a **User**, I would like **to be able to read blog posts full of useful information**, so that **I can keep upto date on the company and learn new information**

### Acceptance Criteria
-	Acceptance Criteria 1
**Given** that I am a user on the site
**When** I navigate to the blog post page
**Then** I am presented with all the blog posts that are available
-	Acceptance Criteria 2
**Given** that I am a user on the blog posts page
**When** I click on a blog post
**Then** I am taken to the full post details

### Tasks
-	[ ] Task 1 – Develop a blog post page to display all the blog posts
-	[ ] Task 2 – Develop blog post cards to display a summary of each post
-	[ ] Task 3 – Develop a blog post detail page to display the full post
-	[ ] Task 4 – Link the blog card to the detail page for each blog post
-	[ ] Task 5 – Display the blog posts in date order, most recent first

**Comment by MattBCoding** [comment]
Completed on commit 25b9410fc05d73978cc61631b3aec147e7cc7b74
