### ISSUE TITLE
User Story - Delete Blog Post

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/druid-pp5#62]
As a **Employee*, I would like to **be able to delete a blog post**, so that **in the event we need to remove one completely we can take it down from the site**

### Acceptance Criteria
-	Acceptance Criteria 1
**Given** that I am a logged in employee
**When** I navigate to a blog post
**Then** I have the option to remove the post
-	Acceptance Criteria 2
**Given** that I am a logged in employee
**When** I select the remove option on a blog post
**Then** the post is removed from the site

### Tasks
-	[x] Task 1 – Develop an option in the blog post edit page to delete the post
-	[x] Task 2 – Develop the functionality to delete the post from the database
-	[x] Task 3 – Restrict access to the functionality to employee users

**Comment by MattBCoding** [comment]
Completed on commit 2a6e125ea56dba6698eae0a0db45d202e630610b
